### ISSUE TITLE
Change bullet and spawner _Process to _Physics_process

### ISSUE THREAD

**Issue by LandstalkerZero** [quinnvoker/qurobullet#15]
I created a replay system using _Physics_process, all character movements are recorded frame by frame, but the bullet in this module does not change speed from changing fps, and i think a delta is used which breaks the replay system
Spawner changes speed, but I don’t understand if it works correctly.
Is there a way to change this in godot without changing source code

**Comment by quinnvoker** [comment]
Hi, and thanks for the bug report! I really appreciate hearing from people using this module in their projects. :)

I'd love to patch up qurobullet and solve this problem for you, but I need some clarification first.

Currently, all bullet movement and collision detection already occurs in physics process, so I need a bit more information about your replay system to figure out what's causing the issue. You mention "changing fps" with the replays, but I'm not sure what you're doing exactly. Are you adjusting Godot's timescale to make slow motion effects, and that's causing things to desync?

Once I know what you're trying to do exactly, I can probably solve this issue! 

If it's not too much to ask, if you could give me a sample scene that demonstrates the issue you're having, I could use it to make sure the problem is fixed before I update the repo.

**Comment by LandstalkerZero** [comment]
In project settin i change Physics/Common/Physics fps to change game speed
i dont use _process(delta) or delta
my project (litle clearing it but still look awful):
https://drive.google.com/drive/folders/1DHBSaan-J2pguqQvx5AauneECWit_lJz?usp=sharing 
wasd to move
replay in project, just press replay, to write new press start move charater and press save, after press replay or start you need reload project to replay or start new record becose it still not finish
well change fps to 30 or 240 and look what happend after press replay (by defoult 60 )

**Comment by quinnvoker** [comment]
Thanks for getting back to me! I can't look at your example until I'm at my computer (and I don't have much time to work on qurobullet during weekdays), but this information helps me understand the situation a lot better!

Unfortunately, fixing this is not so simple. Bullet physics processing in qurobullet makes use of delta in its calculations, to increase stability in performance, to allow users to get the same behaviour regardless of framerate (so other devs could make their game run at a base of 30fps or 120fps and get roughly the same behaviour in game), and create smoothly interpolated slow motion and fast forward effects at different timescales. Your slow-mo system relies on the bullets moving the same distance per frame, regardless of how long that frame takes to complete.

So, the core of the problem is that qurobullet is built around time, and your system is built around frames. 

While I could potentially put in a bandaid type solution to make it work the way you need, it goes against the design of the rest of the program. Also, I don't think changing physics fps in a live game is recommended, and I don't wanna code things in a way that goes against Godot's usual workflow. So, I'm sorry, but I won't implement a fix to this.

Instead, all I can do is recommend you use Engine.time_scale for your game speed changes instead of changing physics FPS (which you'll notice will make your slow mo a lot smoother), and rework your replay system to be based on time rather than frames. Feel free to ask me for advice if you try that and run into issues.

**Comment by quinnvoker** [comment]
I closed the issue, but this thread will stay open in case you have any questions!

**Comment by LandstalkerZero** [comment]
Thank to tell me about Engine.time_scale, timer work good with this (0.012 to 60 tick per second).

**Comment by quinnvoker** [comment]
No problem! I'm happy that time scale is helpful for you!

**Comment by LandstalkerZero** [comment]
So i try hard as can but unfortunately replay system with this module is imposible (right now).
Problem is when change forse fps(_process(delta)) delta change variable and this is good, i actualy can identify each frame fps but  when i change Engine.time_scale delta change variable again and engine go broke(as expected)
```
func _process(delta):
T = (((1/ delta)*3)*2 / 120 to get current time_scale from fps)
Engine.time_scale = T
```
After all change fps and check frame using _process without predict drop fps just broke replay.
Some time godot give intrestiong expirience -_-
Mayby later i found how create replay system with this module

**Comment by LandstalkerZero** [comment]
this issue is totaly close, i`am idiot
func _physics_process(delta):
for i in range(4)
frame +=1
this give 240 fps and replay work perfect
