### ISSUE TITLE
[Question] Current state, Godot 4.0?

### ISSUE THREAD

**Issue by SSebigo** [quinnvoker/qurobullet#26]
Hey @quinnvoker,

I stumbled upon your old post on r/gamedev, I'm quite interested in this module since it could really help with a project I'm working on currently.
So I wanted to know 2 things:
- Is the module up-to-date and ready for production? The last commit was 3 months ago so I'm worried maybe you've abandoned the project.
- Do you have anything planned for Godot 4.0? Performance optimization? Pre-compiled version?

On a side note, I really like the simplicity it has for the "end-user", great work overall.

If anything is planned, I'll try to help, I'll just need to get my C++ back together.

**Comment by quinnvoker** [comment]
Hi there, thanks for getting in touch!

I'm not actively working on this project at the moment, but I wouldn't call it abandoned either. 

I don't have any additional features to add planned or anything, and I recently got my first job as a programmer and am still settling into it, so I don't have as much time to put into projects like this as I did last year.

However, I plan to at least keep `qurobullet` up-to-date and compatible with the latest releases of Godot. To my knowledge, this module is fully compatible with 3.2 and is generally stable (though I haven't done a lot of exhaustive testing since last summer, I do check if it works in new versions, and there's not a whole lot that can really go wrong with it).

As for 4.0, there's a branch called `testing/godot-4.0` for that purpose. 4.0 changed a number of things internally and so variable types and such had to be updated for compatibility. So far it seems to work okay, though again, no exhaustive testing since the last time I worked on this, 4.0 was still in a very early/buggy state.

No further optimizations planned, as I think it's already working about as efficiently as Godot's physics server can handle at this point. The module may benefit from any physics optimizations made in Godot itself though.

All in all, I think the module is stable enough for use in production. If you run into any unexpected issues though, feel free to get in touch and I can sort them out and make any necessary updates.

Cheers and good luck with your project!

**Comment by SSebigo** [comment]
Using the latest ``Godot`` code pushed on their master branch, when compiling I get the error ``include : 'core/object.h' : No such file or directory`` in the ``bullet.h`` file.

**Comment by quinnvoker** [comment]
If you're using Godot's `master` branch, are you using the `testing/godot-4.0` branch of qurobullet? The `master` branch of qurobullet is only compatible with the source of Godot 3.2.x.

If that's not it, let me know and I'll check it out.

**Comment by SSebigo** [comment]
@quinnvoker Ah shit didn't check branches, I'll try ``testing/godot-4.0`` asap.

**Comment by quinnvoker** [comment]
Okay, makes sense! Thanks for letting me know, that's another update that's gonna have to happen in the 4.0 testing branch then. I'll see if I can tackle that this weekend.

I'm curious though, if you're looking for something stable enough for full game production in qurobullet, why are you using the unstable pre-alpha of Godot 4.0 on `master` and not one of the stable releases of 3.2.x?

You can find the source code of stable releases here if you need it: https://github.com/godotengine/godot/releases

**Comment by SSebigo** [comment]
@quinnvoker Actually I didn't even think on which branch I was when I cloned ``Godot`` but yesterday for some reason it made sense for me to clone the latest changes... I was probably tired since I did it at 1 am.

I'll try again tonight on a 3.2.x release,

**Comment by quinnvoker** [comment]
Patched the `testing/godot-4.0` branch to be compatible with Godot `master` currently. Still wouldn't recommend using Godot's `master` branch yet, as it's still prone to freeze/hang etc. But it should work with qurobullet for now at least.
