### ISSUE TITLE
rigid body bullets?

### ISSUE THREAD

**Issue by bendnuts** [quinnvoker/qurobullet#29]
i like it when bullets collide with enemy bullets- it gives you a sense of control.

**Comment by quinnvoker** [comment]
qurobullet is not designed to work this way, unfortunately; it's built to handle huge numbers of bullets with high performance. As such, they're written as plain Objects for speed, and even just implementing them as plain Nodes drastically increases the processing power each bullet requires, let alone as RigidBody nodes that would take additional physics processing and have to check for collisions with each other... I have no plans to implement a feature like this anytime soon.

That said, it's not impossible to accomplish what you want with this module. Since in most games, you don't need players to be capable of firing complicated volley patterns like enemies do, you could use qurobullet specifically for the enemy bullets, and write your own simpler script for spawning bodies (or areas for better performance) for player bullets that can collide with qurobullet bullets.

You could even make use of a spawner detached from the bullet server and use its signals to spawn your custom bullets, if you wanna get fancy with it.
