### ISSUE TITLE
Unable to compile android template with qurobulet module. 

### ISSUE THREAD

**Issue by Rietly** [quinnvoker/qurobullet#30]
![image](https://user-images.githubusercontent.com/92178640/155266828-e9942a6d-5812-4f05-8515-3bb06089d80d.png)

On Windows, there are no errors with it, and if I remove the module, then the export android template is created without errors. Can this be fixed somehow? Sorry in advance for my English.

**Comment by quinnvoker** [comment]
Thanks for letting me know about this! I haven't tried building android templates since this module was first released in 2020, so I've probably missed some breaking changes in Godot. I likely won't get to look into this until this weekend, but at that point I'll give compiling an android template a shot and fix any issues run into.

**Comment by quinnvoker** [comment]
I've made some pre-built binaries for editors and templates on various platforms for Godot 3.4.4, including android templates. They can be found here: https://github.com/quinnvoker/godot-qurobullet/releases/tag/v1.1-godot-3.4.4
